gameonlock/urls.py
import datetime

from allauth.account.decorators import secure_admin_login
from django.conf import settings
from django.conf.urls import handler400, handler403, handler404, handler500
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import include, path
from django.utils.translation import gettext_lazy as _
from django.views.decorators.cache import cache_page
from django.views.generic import TemplateView
from django.views.i18n import JavaScriptCatalog, set_language
from puput import urls as puput_urls
from wagtail import urls as wagtail_urls
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.admin.views.account import LoginView as WagtailLoginView
from wagtail.documents import urls as wagtaildocs_urls

import sportsbetting.urls

from . import views

admin.autodiscover()
admin.site.login = secure_admin_login(admin.site.login)

allauth_urls = [
	path(_("login/"), views.LoginView.as_view(), name="account_login"),
	path(_("signup/"), views.SignupView.as_view(), name="account_signup"),
]

api_urls = [
	path(r"sports/", include(sportsbetting.urls.apipatterns)),
]

internationalized_patterns = i18n_patterns(
	path(_("accounts/"), include((allauth_urls, "custom_allauth"))),
	path(_("accounts/"), include("allauth.urls")),
	path(_("sports/"), include("sportsbetting.urls")),
	# path(_("shop/"), include(apps.get_app_config("oscar").urls[0])),
	path(_("dashboard/"), views.DashboardView.as_view(), name="dashboard"),
	path(
		_("dashboard/bet-history/"),
		views.PlayHistoryView.as_view(),
		name="play_history",
	),
	path(
		_("dashboard/transaction-history/"),
		views.TransactionHistoryView.as_view(),
		name="transaction_history",
	),
	path(_("dashboard/settings/"), views.SettingsView.as_view(), name="settings"),
	path(_("contact/"), views.ContactView.as_view(), name="contact"),
	path(_("about/"), TemplateView.as_view(template_name="todo"), name="about"),
	path(
		_("terms/"),
		TemplateView.as_view(
			template_name="terms.html",
			extra_context={
				"title": _("Terms and Conditions"),
				"last_updated": datetime.date(year=2025, day=1, month=7),
			},
		),
		name="terms",
	),
	path(
		_("privacy/"),
		TemplateView.as_view(
			template_name="privacy.html",
			extra_context={
				"title": _("Privacy Policy"),
				"last_updated": datetime.date(year=2025, day=1, month=7),
			},
		),
		name="privacy",
	),
	path(
		"jsi18n/",
		cache_page(86400, key_prefix="jsi18n")(JavaScriptCatalog.as_view()),
		name="javascript-catalog",
	),
	# path(_('search/'), search_views.search, name='search'), # TODO: Implement Wagtail search capability
	path("", include(wagtail_urls)),
	path("", include(puput_urls)),
	prefix_default_language=False,
)

urlpatterns = [
	path("admin/", admin.site.urls),
	path("csp-report/", views.csp_report_view, name="csp_report"),
	path("i18n/set_language/", set_language, name="set_language"),
	path(
		"cms/login/",
		secure_admin_login(WagtailLoginView.as_view()),
		name="wagtailadmin_login",
	),
	path("cms/", include(wagtailadmin_urls)),
	path("documents/", include(wagtaildocs_urls)),
	path("payment/", include("golpayment.urls")),
	path("api/", include((api_urls, "api"), namespace="api")),
] + internationalized_patterns


if "silk" in settings.INSTALLED_APPS:
	urlpatterns.append(path("silk/", include("silk.urls", namespace="silk")))

if settings.DEBUG:
	import debug_toolbar
	from django.conf.urls.static import static
	from django.contrib.staticfiles.urls import staticfiles_urlpatterns

	# Serve static and media files from development server
	urlpatterns += staticfiles_urlpatterns()
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
	urlpatterns = [
		path("__debug__/", include(debug_toolbar.urls)),
		path("400/", handler400, kwargs={"exception": Exception("Bad request")}),
		path("403/", handler403, kwargs={"exception": Exception("Forbidden")}),
		path("404/", handler404, kwargs={"exception": Exception("Page not found")}),
		path("500/", handler500, kwargs={"exception": Exception("Server error")}),
	] + urlpatterns

sportsbetting/urls.py
from django.urls import path

from . import views

app_name = "sportsbetting"

apipatterns = [
	path("my-betslip/", views.api.UserBetSlipsView.as_view(), name="my_betslip"),
]

urlpatterns = [
	path("bet/", views.BettingView.as_view(), name="bet"),
	path("plays/create/", views.PlayCreateUpdateView.as_view(), name="play_create"),
	# path("plays/update/<int:id>/", views.PlayCreateUpdateView.as_view(), name="play_update"),
	# path("plays/delete/", views.PlayDeleteView.as_view(), name="play_delete"),
	# path("paypal/", include("paypal.standard.ipn.urls")),
	# path("payment_complete/", views.payment_complete, name="payment_complete"),
	# path("payment_cancelled/", views.payment_cancelled, name="payment_cancelled"),
]

templates/peredion/elements/banner.html
{% load static i18n view_breadcrumbs wagtailroutablepage_tags wagtailimages_tags %}
<div class="prd-breadcrumb">
    {% if page and page.header_image %}
        {% image page.header_image fill-1500x250 as header_image %}
        <img class="position-absolute top-0 start-0 w-100 h-100 object-fit-cover"
             alt="{{ page.header_image.title }}"
             src="{{ header_image.url }}"
             nonce="{{ request.csp_nonce }}">
    {% endif %}
    <div class="brd-shape">
        <div class="brd-img brd-img-1"
             data-aos="fade-right"
             data-aos-delay="200"
             data-aos-duration="500"
             data-aos-easing="ease-in">
            <img src="{% static 'peredion/images/breadcrumb/brd-img-1.png' %}"
                 alt=""
                 nonce="{{ request.csp_nonce }}">
        </div>
        <div class="brd-img brd-img-2"
             data-aos="fade-left"
             data-aos-delay="200"
             data-aos-duration="500"
             data-aos-easing="ease-in">
            <img src="{% static 'peredion/images/breadcrumb/brd-img-2.png' %}"
                 alt=""
                 nonce="{{ request.csp_nonce }}">
        </div>
    </div>
    <div class="container">
        <div class="brd-content">
            <div data-aos="fade-up"
                 data-aos-delay="200"
                 data-aos-duration="500"
                 data-aos-easing="ease-in">
                <span class="sub-title">
                    {% if page %}
                        {{ page.title }}
                    {% else %}
                        {{ title }}
                    {% endif %}
                </span>
            </div>
            <h2 class="title"
                data-aos="fade-up"
                data-aos-delay="350"
                data-aos-duration="500"
                data-aos-easing="ease-in">
                {% if page %}
                    {{ page.subtitle|default:'' }}
                {% else %}
                    {{ subtitle|default:'' }}
                {% endif %}
            </h2>
            <div class="page-direction">
                {% if not page %}
                    {% render_breadcrumbs %}
                {% else %}
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            {% for ancestor in page.get_ancestors.inclusive.live %}
                                {% if not url or forloop.counter == breadcrumbs_total %}
                                    <li class="breadcrumb-item
                                               {% if forloop.counter == breadcrumbs_total %}active{% endif %}"
                                        {% if forloop.counter == breadcrumbs_total %}aria-current="page"{% endif %}>{{ ancestor.title|safe }}</li>
                                {% else %}
                                    <li class="breadcrumb-item">
                                        <a href="{{ ancestor.url }}">{{ ancestor.title|safe }}</a>
                                    </li>
                                {% endif %}
                            {% endfor %}
                        </ol>
                    </nav>
                {% endif %}
            </div>
        </div>
    </div>
</div>

templates/peredion/elements/footer.html
{% load static i18n %}
<div class="footer">
    <div class="global-shape style-4">
        <img src="{% static 'peredion/images/shapes/shape-1.png' %}"
             alt=""
             data-aos="fade-left"
             data-aos-duration="500"
             data-aos-offset="200"
             data-aos-easing="ease-in"
             data-aos-delay="500"
             nonce="{{ request.csp_nonce }}">
    </div>
    <div class="footer-top">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-xl-6 col-lg-6 col-md-8 col-sm-9">
                    <div class="part-about">
                        <div class="footer-logo"
                             data-aos="fade-up"
                             data-aos-delay="100"
                             data-aos-duration="500"
                             data-aos-easing="ease-in">
                            <a href="index.html">
                                <img src="{% static 'peredion/images/logo/mobile-logo.png' %}"
                                     alt="{% trans 'logo' %}"
                                     class="logo"
                                     nonce="{{ request.csp_nonce }}">
                            </a>
                        </div>
                        <p data-aos="fade-up"
                           data-aos-delay="150"
                           data-aos-duration="500"
                           data-aos-easing="ease-in">
                            {% blocktrans %}
                            This allows bettors to bet over or under the bookmaker's score,
                            <br />
                            and indicate what they believe the difference in points will be.
                           {% endblocktrans %}
                        </p>
                        <ul class="importants-links">
                            <li class="single-link"
                                data-aos="fade-up"
                                data-aos-delay="200"
                                data-aos-duration="500"
                                data-aos-easing="ease-in">
                                <a href="{% url 'privacy' %}">{% trans 'privacy policy' %}</a>
                            </li>
                            <li class="single-link"
                                data-aos="fade-up"
                                data-aos-delay="250"
                                data-aos-duration="500"
                                data-aos-easing="ease-in">
                                <a href="{% url 'terms' %}">{% trans 'terms' %}</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-bottom">
        <div class="container">
            <div class="footer-bottom-content">
                <p class="copyright-text">
                    {% now "Y" as current_year %}
                    {% blocktrans %}Copyright © {{ current_year }}. All Right Reserved By Game-on-Lock{% endblocktrans %}
                </p>
                <ul class="social-link">
                    <li class="single-social">
                        <a href="#0">
                            <i class="fa-brands fa-facebook-f"></i>
                        </a>
                    </li>
                    <li class="single-social">
                        <a href="#0">
                            <i class="fa-brands fa-twitter"></i>
                        </a>
                    </li>
                    <li class="single-social">
                        <a href="#0">
                            <i class="fa-brands fa-pinterest-p"></i>
                        </a>
                    </li>
                </ul>
                <div class="footer-menu">
                    <ul>
                        <li>
                            <a href="/" class="single-menu">{% trans 'home' %}</a>
                        </li>
                        <li>
                            <a href="#TODO" class="single-menu">{% trans 'about' %}</a>
                        </li>
                        <li>
                            <a href="{% url 'sportsbetting:bet' %}" class="single-menu">{% trans 'bet' %}</a>
                        </li>
                        <li>
                            <a href="#TODO" class="single-menu">{% trans 'blog' %}</a>
                        </li>
                        <li>
                            <a href="#TODO" class="single-menu">{% trans 'contact' %}</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

templates/peredion/elements/header.html
{% load static i18n gameonlock %}
{% get_available_languages as languages %}
{# TODO: header animations not work #}
<header class="header header-fixed animated"
        x-data="{ isVisible: true, lastScrollY: window.scrollY, threshold: 10, debounceTimeout: null,  handleScroll() { const current = window.scrollY;  if (Math.abs(current - this.lastScrollY) <= this.threshold) return;  this.isVisible = current < this.lastScrollY || current < 100; this.lastScrollY = current; },  init() { window.addEventListener('scroll', () => { if (this.debounceTimeout) clearTimeout(this.debounceTimeout); this.debounceTimeout = setTimeout(() => this.handleScroll(), 100); }); } };"
        x-init="init()"
        :class="{ 'animate__fadeInDown': isVisible, 'animate__fadeOutUp': !isVisible }">
    <div class="top-bar">
        <div class="container">
            <div class="row justify-content-between">
                <div class="col-xl-5 col-lg-5 col-md-7">
                    <div class="left-side">
                        {% if request.user.is_authenticated %}
                            <div class="single-bar">
                                <span class="dashboard-overview">
                                    <span class="part-icon">
                                        <i class="fa-solid fa-circle-user"></i>
                                    </span>
                                    <span class="part-text">{% trans 'hi,' %} <span class="user-name">{{ request.user }}</span></span>
                                </span>
                            </div>
                            {% if request.user.email %}
                                <div class="single-bar">
                                    <span class="dashboard-overview">
                                        <span class="part-icon">
                                            <i class="fa-solid fa-envelope"></i>
                                        </span>
                                        <span class="part-text">{{ request.user.email }}</span>
                                    </span>
                                </div>
                            {% endif %}
                        {% endif %}
                        <div class="single-bar dropdown"
                             x-data="{ currentLang: '{{ request.LANGUAGE_CODE }}' }">
                            <a href="javascript:void(0);"
                               role="button"
                               id="languageMenuLink"
                               data-bs-toggle="dropdown"
                               aria-expanded="false"
                               class="dashboard-overview">
                                <span class="part-icon">
                                    <i class="fa-solid fa-globe"></i>
                                </span>
                                <span class="part-text lang-display" x-text="currentLang"></span>
                            </a>
                            {% if languages|length > 1 %}
                                <ul class="dropdown-menu lang-item" aria-labelledby="languageMenuLink">
                                    {% for lang_code, lang_name in languages %}
                                        {% if lang_code != request.LANGUAGE_CODE %}
                                            <li>
                                                <form method="post" action="{% url 'set_language' %}" class="language-form">
                                                    {% csrf_token %}
                                                    <input type="hidden" name="language" value="{{ lang_code }}">
                                                    <button type="submit"
                                                            class="dropdown-item"
                                                            x-on:click="currentLang = '{{ lang_code|language_name_local }}'">
                                                        {{ lang_code|language_name_local }}
                                                    </button>
                                                </form>
                                            </li>
                                        {% endif %}
                                    {% endfor %}
                                </ul>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="col-xl-5 col-lg-5 col-md-5">
                    <div class="right-side"
                         x-data="{ date: '', month: '', year: '', hours: '', minutes: '', seconds: '', monthNames: ['Jan', 'Feb', 'March', 'Apr', 'May', 'June', 'July', 'Aug', 'Sept', 'Oct', 'Nov', 'Dec'], updateClock() { const now = new Date(); this.date = now.getDate(); this.month = this.monthNames[now.getMonth()]; this.year = now.getFullYear(); this.hours = now.getHours().toString().padStart(2, '0'); this.minutes = now.getMinutes().toString().padStart(2, '0'); this.seconds = now.getSeconds().toString().padStart(2, '0'); } }"
                         x-init="updateClock(); setInterval(() => updateClock(), 1000)">
                        <div class="single-bar">
                            <span class="part-icon">
                                <i class="fa-solid fa-calendar-days"></i>
                            </span>
                            <span class="part-text">
                                <span x-text="date"></span>
                                <span x-text="month"></span>
                                <span x-text="year"></span>
                            </span>
                        </div>
                        <div class="single-bar">
                            <span class="part-icon">
                                <i class="fa-solid fa-clock"></i>
                            </span>
                            <span class="part-text">
                                <span class="timer" x-text="hours"></span>:<span class="timer" x-text="minutes"></span>:<span class="timer" x-text="seconds"></span>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="mobile-navbar">
        <div class="container">
            <div class="row">
                <div class="col-6 col-xl-none col-lg-none col-md-block d-flex align-items-center">
                    <a href="/" class="mobile-logo">
                        <img src="{% static 'peredion/images/logo/mobile-logo.png' %}"
                             alt="{% trans 'logo' %}"
                             nonce="{{ request.csp_nonce }}">
                    </a>
                </div>
                <div class="col-6 col-xl-none col-lg-none col-lg-block">
                    <button class="navbar-toggler"
                            type="button"
                            data-bs-toggle="collapse"
                            data-bs-target="#navbarSupportedContent"
                            aria-controls="navbarSupportedContent"
                            aria-expanded="false"
                            aria-label="{% trans 'Toggle navigation' %}"
                            x-data="{ isOpen: false }"
                            x-on:click="isOpen = !isOpen">
                        <i class="fa-solid"
                           :class="{ 'fa-bars-staggered': isOpen, 'fa-bars': !isOpen }"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>
    <div class="mainmenu">
        <div class="container">
            <nav class="navbar navbar-expand-lg">
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <div class="scalation">
                        <div class="row">
                            <div class="col-xl-5 col-lg-5">
                                <ul class="navbar-nav nn-left">
                                    <li class="nav-item">
                                        <a class="nav-link
                                                  {% if request.path == '/' %}active{% endif %}"
                                           href="/">{% trans 'home' %}</a>
                                    </li>
                                    <li class="nav-item">
                                        {# TODO: this should direct to a wagtail page #}
                                        {% url 'about' as url %}
                                        <a class="nav-link
                                                  {% if request.path == url %}active{% endif %}"
                                           href="{{ url }}">{% trans 'about us' %}</a>
                                    </li>
                                    <li class="nav-item">
                                        {% url 'sportsbetting:bet' as url %}
                                        <a class="nav-link
                                                  {% if request.path == url %}active{% endif %}"
                                           href="{{ url }}">{% trans 'bets' %}</a>
                                    </li>
                                    <li class="nav-item">
                                        {% url 'contact' as url %}
                                        <a class="nav-link
                                                  {% if request.path == url %}active{% endif %}"
                                           href="{{ url }}">{% trans 'contact us' %}</a>
                                    </li>
                                </ul>
                            </div>
                            <div class="col-2 col-lg-2 d-xl-block d-lg-block d-md-none">
                                <div class="logo">
                                    <a href="/">
                                        <img src="{% static 'peredion/images/logo/logo-1.png' %}"
                                             alt="{% trans 'logo' %}"
                                             nonce="{{ request.csp_nonce }}">
                                    </a>
                                </div>
                            </div>
                            <div class="col-xl-5 col-lg-5">
                                <ul class="navbar-nav nn-right">
                                    <li class="nav-item dropdown">
                                        {# TODO: direct to wagtail articles; detect active #}
                                        <a class="nav-link" href="javascript:void(0);">{% trans 'blog' %}</a>
                                    </li>
                                    <li class="nav-item">
                                        {% url 'faq' as url %}
                                        <a class="nav-link
                                                  {% if request.path == url %}active{% endif %}"
                                           href="{{ url }}">{% trans 'faq' %}</a>
                                    </li>
                                    {% if request.user.is_authenticated %}
                                        <li class="nav-item dropdown ms-auto">
                                            <a class="nav-link dropdown-toggle
                                                      {% if is_account_section_active %}active{% endif %}"
                                               href="javascript:void(0);"
                                               id="dashboardDropdown"
                                               role="button"
                                               data-bs-toggle="dropdown"
                                               aria-expanded="false">{% trans 'account' %}</a>
                                            <ul class="dropdown-menu" aria-labelledby="dashboardDropdown">
                                                <li>
                                                    <a class="dropdown-item" href="{% url 'dashboard' %}">{% trans 'dashboard' %}</a>
                                                </li>
                                                <li>
                                                    <a class="dropdown-item" href="{% url 'play_history' %}">{% trans 'bet history' %}</a>
                                                </li>
                                                <li>
                                                    <a class="dropdown-item" href="{% url 'transaction_history' %}">{% trans 'transaction history' %}</a>
                                                </li>
                                                <li>
                                                    <a class="dropdown-item" href="{% url 'settings' %}">{% trans 'settings' %}</a>
                                                </li>
                                            </ul>
                                        </li>
                                    {% else %}
                                        <li class="nav-item ms-auto">
                                            {% url 'account_login' as url %}
                                            <a class="nav-link
                                                      {% if request.path == url %}active{% endif %}"
                                               href="{{ url }}"><i class="fa-solid fa-user"></i>{% trans 'sign in' %}</a>
                                        </li>
                                    {% endif %}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </nav>
        </div>
    </div>
</header>

templates/peredion/elements/preloader.html
{% load static i18n %}
<div class="preloader"
     x-data="{ visible: true }"
     x-show="visible"
     x-init="document.addEventListener('DOMContentLoaded', () => { setTimeout(() => { visible = false; document.dispatchEvent(new CustomEvent('PreloaderFinished')); }, 1000); });"
     x-transition.opacity.duration.1000ms>
    <div class="icon">
        <img src="{% static 'peredion/images/preloader/preload-1.gif' %}"
             alt=""
             nonce="{{ request.csp_nonce }}">
        <img src="{% static 'peredion/images/preloader/preload-2.gif' %}"
             alt=""
             nonce="{{ request.csp_nonce }}">
        <img src="{% static 'peredion/images/preloader/preload-5.gif' %}"
             alt=""
             nonce="{{ request.csp_nonce }}">
        <img src="{% static 'peredion/images/preloader/preload-4.gif' %}"
             alt=""
             nonce="{{ request.csp_nonce }}">
        <img src="{% static 'peredion/images/preloader/preload-3.gif' %}"
             alt=""
             nonce="{{ request.csp_nonce }}">
    </div>
    <span class="text">{% trans 'Game-on-Lock is loading' %}</span>
</div>